# Generated by CodiumAI

import pytest

from addict import Dict as Addict

from dacutil import (
    Addict,
    datediff,
    get_config,
    check_mod11,
    df_strip,
    worker,
)


class TestGetConfig:
    # Retrieves configuration from a file URI with no authentication or headers
    def test_retrieves_config_from_filepath(self):
        # Arrange
        files = [
            "test/config.ini",
            "test/config.json",
            "file://test/config.ini",
            "file://test/config.json",
            "file://test/config.toml",
            "file://test/config.yaml",
        ]
        expected_config = Addict({"section": {"key": "value"}})
        for filepath in files:
            # Act
            config = get_config(filepath)

            # Assert
            assert isinstance(config, Addict)
            assert config == expected_config
