# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  pip:
    - pip install .
  test:
    cmds:
      # - pip install .
      - poetry run pytest

  update:
    - poetry update

  install:
    - poetry install

  build:
    cmds:
      - poetry build

  pub:
    cmds:
      - task pip test
      - task build
      - poetry publish
