# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  test:
    cmds:
      - pip install .
      - poetry run pytest

  update:
    - poetry update

  install:
    - poetry install

  build:
    cmds:
      - poetry build

  publish:
    cmds:
      - poetry publish
